#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=2
#$ -N inferenceQwen2.5-3B
conda activate LLM
bash inference.sh 'qwen2.5-3b' "None"   0
bash inference.sh 'qwen2.5-3b' "None"   1
bash inference.sh 'qwen2.5-3b' "redf"   0
bash inference.sh 'qwen2.5-3b' "redf"   1
bash inference.sh 'qwen2.5-3b' "are2df" 0
bash inference.sh 'qwen2.5-3b' "are2df" 1
bash inference.sh 'qwen2.5-3b' "re2df"  0
bash inference.sh 'qwen2.5-3b' "re2df"  1