#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=2
#$ -N inference-7b
conda activate LLM
bash inference.sh 'llama-3.1-70b' "None"   0
bash inference.sh 'llama-3.1-70b' "None"   1
bash inference.sh 'llama-3.1-70b' "redf"   0
bash inference.sh 'llama-3.1-70b' "redf"   1
bash inference.sh 'llama-3.1-70b' "are2df" 0
bash inference.sh 'llama-3.1-70b' "are2df" 1
bash inference.sh 'llama-3.1-70b' "re2df"  0
bash inference.sh 'llama-3.1-70b' "re2df"  1