#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@qa-a100-003
#$ -l gpu=2
#$ -N inferenceLlama-3.1-70B
conda activate MO
bash inference.sh 'llama-3.1-70b' "None"      0 10000
bash inference.sh 'llama-3.1-70b' "None"      1 10000
bash inference.sh 'llama-3.1-70b' "chatdrug"  0 10000
bash inference.sh 'llama-3.1-70b' "chatdrug"  1 10000
bash inference.sh 'llama-3.1-70b' "agentdrug" 0 10000
bash inference.sh 'llama-3.1-70b' "agentdrug" 1 10000