#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@qa-a100-003
#$ -l gpu=2
#$ -N inferenceQwen2.5-3B
conda activate MolOpt
bash inference.sh 'qwen2.5-3b' "None"   0 10000
bash inference.sh 'qwen2.5-3b' "None"   1 10000
bash inference.sh 'qwen2.5-3b' "redf"   0 10000
bash inference.sh 'qwen2.5-3b' "redf"   1 10000
bash inference.sh 'qwen2.5-3b' "are2df" 0 10000
bash inference.sh 'qwen2.5-3b' "are2df" 1 10000