#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@@lucy_a100
#$ -l gpu=2
#$ -N inferenceLlama-3.1-8B
conda activate LLM
bash inference.sh 'llama-3.1-8b' "None"   0
bash inference.sh 'llama-3.1-8b' "None"   1
bash inference.sh 'llama-3.1-8b' "redf"   0
bash inference.sh 'llama-3.1-8b' "redf"   1
bash inference.sh 'llama-3.1-8b' "are2df" 0
bash inference.sh 'llama-3.1-8b' "are2df" 1
bash inference.sh 'llama-3.1-8b' "re2df"  0
bash inference.sh 'llama-3.1-8b' "re2df"  1