#!/bin/bash
#$ -M kle3@nd.edu
#$ -m be
#$ -pe smp 8
#$ -q gpu@qa-a100-003
#$ -l gpu=2
#$ -N inferenceLlama-3.1-08B
conda activate MO
bash inference.sh 'llama-3.1-8b' "None"   0 10000
bash inference.sh 'llama-3.1-8b' "None"   1 10000
bash inference.sh 'llama-3.1-8b' "redf"   0 10000
bash inference.sh 'llama-3.1-8b' "redf"   1 10000
bash inference.sh 'llama-3.1-8b' "are2df" 0 10000
bash inference.sh 'llama-3.1-8b' "are2df" 1 10000